trigger:
  - main

pool:
  name: Self-hosted-agent



variables:
  imageName: 'nourhankhalidd/assessment'
  imageTag: 'build-$(Build.BuildId)'

stages:
- template: azure-pipelines/templates/build.yml

- template: azure-pipelines/templates/docker.yml