trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

stages:

- stage: Build
  displayName: 'Build Spring Boot Application'
  jobs:
  - job: MavenBuild
    displayName: 'Maven Build'
    steps:

    - checkout: self

    - task: Maven@4
      displayName: 'Build Application'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish JAR Artifact'
      inputs:
        PathtoPublish: 'target'
        ArtifactName: 'spring-boot-app'
        publishLocation: 'Container'


- stage: DockerBuild
  displayName: 'Build Docker Image'
  dependsOn: Build
  jobs:
  - job: Docker
    displayName: 'Docker Build'
    steps:

    - checkout: self

    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: build
        Dockerfile: '**/Dockerfile'
        tags: |
          assessment-app:$(Build.BuildId)