trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'nourhankhalidd/assessment'
  imageTag: 'build-$(Build.BuildId)'

stages:

# ==========================
# Build Stage
# ==========================
- stage: Build
  displayName: 'Build, Test & Sonar Analysis'

  jobs:
  - job: MavenBuild
    displayName: 'Build Spring Boot Application'

    steps:

    - checkout: self
      fetchDepth: 0

    # Maven Cache
    - task: Cache@2
      displayName: 'Cache Maven Dependencies'
      inputs:
        key: 'maven | "$(Agent.OS)" | pom.xml'
        restoreKeys: |
          maven | "$(Agent.OS)"
        path: $(HOME)/.m2/repository

    # Prepare SonarCloud
    - task: SonarCloudPrepare@3
      displayName: 'Prepare SonarCloud Analysis'
      inputs:
        SonarCloud: 'SonarCloud'
        organization: 'nourhankhalidd'
        scannerMode: 'other'
        extraProperties: |
          sonar.projectKey=nourhankhalidd_devops-assessment
          sonar.projectName=devops-assessment

    # Build + Test + Sonar Analysis
    - task: Maven@4
      displayName: 'Build & Test'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean verify'
        sonarQubeRunAnalysis: true

    # Publish Quality Gate
    - task: SonarCloudPublish@3
      displayName: 'Publish Quality Gate'
      inputs:
        pollingTimeoutSec: '300'

    # Publish Test Results
    - task: PublishTestResults@2
      displayName: 'Publish Test Results'
      inputs:
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        testRunTitle: 'Spring Boot Unit Tests'

    # Publish JAR
    - task: PublishBuildArtifacts@1
      displayName: 'Publish JAR Artifact'
      inputs:
        PathtoPublish: 'target'
        ArtifactName: 'spring-boot-app'
        publishLocation: 'Container'

# ==========================
# Docker Stage
# ==========================
- stage: Docker
  displayName: 'Docker Build, Security Scan & Push'

  dependsOn: Build

  jobs:

  - job: DockerBuild
    displayName: 'Docker Build'

    steps:

    - checkout: self

    # Build Docker Image
    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: build
        Dockerfile: '**/Dockerfile'
        repository: $(imageName)
        tags: |
          $(imageTag)
          latest

    # Trivy Scan
    - script: |
        docker run --rm \
          -v /var/run/docker.sock:/var/run/docker.sock \
          aquasec/trivy:0.72.0 \
          image \
          --severity HIGH,CRITICAL \
          --format table \
          --no-progress \
          --skip-version-check \
          --exit-code 0 \
          $(imageName):$(imageTag)
      displayName: 'Trivy Image Vulnerability Scan'

    # Push Docker Image
    - task: Docker@2
      displayName: 'Push Docker Image'
      inputs:
        command: push
        containerRegistry: 'dockerhub-connection'
        repository: $(imageName)
        tags: |
          $(imageTag)
          latest