---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: assessment-secret
  namespace: default
spec:
  encryptedData:
    APP_SECRET: AgCaZ/0MgRTPi+6WT/5je7xq9+IAlIVZjqmmB/Djmuhv6WyMOX/MnqlkzWtsJD0ov9fHz/jjzKKwOsUSyLMwadYIVR8nisVEZNqZC6VZmdtZE5W1gKgyBjWKIomjLypyLssW0u19NjLkfaDzzsyh2NTulT+bQHnu8KVRSfSTipZXaly2Vo1PVejYmHRTojhqObKy4TndF0mjA/XGIxSD7EqoMs0f/HvSqGkJspSUh+0fmpdem3voAWlKMIe92Hr5EXgFdtiroWYfdzEYaenLo42sPKiVT5Q9zTR7o91ojq/DucaYSMhZyujEYOI07O7I0PTo/E+Wvib/oYwoMo4OlTwMtk7gSj6bOFRmpJ9KN00Z1MoGbthJB0yxZE7pcF2llF8rry8Em7V9TB7q44vlAOulCqp+vVGyaPMbVlBJ2aUEu0yO0XEBFtKG1pc2auDEP6F/hh2XctBN/URiKKb88jCZP79UrlOsz/YSDBo0eJT+8UXR/4dCV8SmdgpKZ2NfziLG8W8f38LrdG2yZ3Zv9UgNwPaJDhXCSgAQfbRh/wbN9uQaNC5PFsUKTx9S2kMYN96Idh9NOCxsQOyfkIP/Nvlhot41Q7YDpx8IonQo2zXEUERQw9kIa5NxiWrv+riNZiWSw2Cjj+oYcTAAAWUX1wJDKTr7zRndaHWpfybjudh9hfqBAEMOqmlTMx18pBIo+oyJVMyVBFccw7SrKCVJBrHieV6L
  template:
    metadata:
      creationTimestamp: null
      name: assessment-secret
      namespace: default
    type: Opaque
